version: 2
updates:
  - package-ecosystem: pip
    directory: /Project_02
    schedule:
      interval: weekly
      day: monday
    groups:
      minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: pip
    directory: /Lesson_13
    schedule:
      interval: weekly
      day: monday
    groups:
      minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: pip
    directory: /Lesson_13 Practice
    schedule:
      interval: weekly
      day: monday
    groups:
      minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
